version: "3.7"

services:
  db-mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3307:3306
    networks:
      - springboot-mysql-net


  spring-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db-mysql
    restart: always
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:
    driver: bridge